DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE CUSTOMER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  customer_number VARCHAR(250) NOT NULL,
  active BOOLEAN NOT NULL default true,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  user_name VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  roles VARCHAR(250) NOT NULL
);

CREATE TABLE ACCOUNT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  active BOOLEAN NOT NULL default true,
  ACCOUNT_NUMBER VARCHAR(50) NOT NULL,
  customer_id INT NOT NULL,
  BALANCE DECIMAL(20, 2) default 0
);

CREATE TABLE TRANSACTION (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  active BOOLEAN NOT NULL default true,
  TRANSACTION_NUMBER VARCHAR(64) NOT NULL, 
  FROM_ACCOUNT_ID INT NULL,
  TO_ACCOUNT_ID INT NOT NULL,
  TRANSACTION_TYPE VARCHAR(64) NOT NULL, 
  TRANSACTION_TIME TIMESTAMP not null,
  AMOUNT DECIMAL(20, 2) default 0
);

